const leadsSampleAll = [
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: true,
    publishedAt: 'Создана 12 января',
    requestsCount: 5,
    watched: 264,
    list: 1268,
  },
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: true,
    publishedAt: 'Создана 12 января',
    watched: 264,
    list: 1268,
    messagesCount: 10,
  },
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: false,
    publishedAt: 'Создана 12 января',
    watched: 264,
    list: 1268,
  },
]

const leadsSampleSimilar = [
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: true,
    publishedAt: 'Создана 12 января',
    requestsCount: 5,
    watched: 264,
    list: 1268,
  },
]

const leadsSampleMyRequests = [
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: true,
    publishedAt: 'Создана 12 января',
    watched: 264,
    list: 1268,
    messagesCount: 10,
  },
]

const leadsSampleAimExecutant = [
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: false,
    publishedAt: 'Создана 12 января',
    watched: 264,
    list: 1268,
  },
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: true,
    publishedAt: 'Создана 12 января',
    requestsCount: 5,
    watched: 264,
    list: 1268,
  },
]

const leadsSampleFavorites = [
  {
    title: 'Куплю 3-х комнатную квартиру на Кипре для инвестиций и ВНЖ',
    location: 'Кипр / Лимассол / Все районы',
    id: '1445',
    price: '158 000 – 230 000',
    year: '2022',
    square: '294 м²',
    rooms: 10,
    sleeps: 6,
    baths: 2,
    yieldCount: 8,
    firstInstallment: '12000 €',
    firstInstallmentPercent: '20%',
    singleCost: '120 €',
    deal: 'Покупка',
    type: 'Жилая | Квартира / апартаменты',
    condition: 'Новая',
    purpose: 'Для инвестиций (сдавать в аренду)',
    isPublished: true,
    isTrue: true,
    publishedAt: 'Создана 12 января',
    watched: 264,
    list: 1268,
    messagesCount: 10,
  },
]

export {
  leadsSampleAll,
  leadsSampleAimExecutant,
  leadsSampleFavorites,
  leadsSampleMyRequests,
  leadsSampleSimilar,
}
