export enum ChatEvents {
  onRoomJoin = 'onRoomJoin',
  onHistoryPageUpdate = 'onHistoryPageUpdate',
  onNewMessage = 'onNewMessage',
  onGetMyProfile = 'onGetMyProfile',
  onGetUserPublicProfile = 'onGetUserPublicProfile',
  onGetUserFullProfile = 'onGetUserFullProfile',
  onMessageDelivered = 'onMessageDelivered',
  onGetRoomsList = 'onGetRoomsList',
  onGetLeadsList = 'onGetLeadsList',
  onGetCompanions = 'onGetCompanions',
  onGetLead = 'onGetLead',
  onContactOpened = 'onFullContactsOpen',
  onRoomUserUpdatedStatus = 'onRoomUserUpdatedStatus',
}
