export { Login } from "./Login";
export { PassRecover1 } from "./PassRecover1";
export { PassRecover2 } from "./PassRecover2";
export { PhoneNum1 } from "./PhoneNum1";
export { PhoneNum2 } from "./PhoneNum2";
export { RegStep1 } from "./RegStep1";
export { RegStep2 } from "./RegStep2";
export { RegStep3 } from "./RegStep3";
export { TechSupport } from "./TechSupport";
